version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: ls -ahl
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      # build the application image
      - run: docker build -f Dockerfile.prod -t stopthebus/app:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push stopthebus/app:$CIRCLE_BRANCH

workflows:
  build:
    jobs:
      - build-medium
