FROM node:15-alpine

WORKDIR /usr/app/

COPY package.json .
COPY yarn.lock .

RUN yarn --frozen-lockfile

COPY . ./

# Build server 
RUN yarn build

ENV PORT=4000

EXPOSE 3000
EXPOSE 4000

CMD ["yarn", "run", "start"]
